import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { extractArray, fetchCompetitionBundle, fetchPlayerBundle, fetchTeamBundle, flattenDisplayRows, normalizeFootballMatch } from "../services/footballApi";

const C={bg:"#080A0C",card:"#111416",card2:"#15191C",border:"#24292D",border2:"#1D2226",red:"#F3262D",redSoft:"rgba(243,38,45,.14)",text:"#FFFFFF",text2:"#D0D2D4",muted:"#92979B",green:"#35C76F"};

function Logo({uri,size=72}){return uri?<Image source={{uri}} resizeMode="contain" style={{width:size,height:size,borderRadius:size/2}} fadeDuration={0}/>:<View style={[s.logoFallback,{width:size,height:size,borderRadius:size/2}]}><Ionicons name="football-outline" size={size*.46} color={C.muted}/></View>;}
function entityTitle(type,entity){return entity?.name||entity?.title||(type==="competition"?"Competition":type==="team"?"Team":"Player");}
function tabsFor(type){return type==="competition"?["OVERVIEW","MATCHES","TABLE","TEAMS","SCORERS"]:type==="team"?["OVERVIEW","MATCHES","SQUAD","STATS","TRANSFERS"]:["OVERVIEW","TRANSFERS","TROPHIES","SIDELINED"];}
function profileObject(value){if(!value)return{};if(Array.isArray(value))return value[0]||{};return value?.data||value?.response?.[0]||value?.response||value?.profile||value;}
function pick(...v){return v.find((x)=>x!==undefined&&x!==null&&x!=="");}

function DataRows({value,limit=30}){const rows=flattenDisplayRows(value).filter((x)=>x?.value!=="[object Object]").slice(0,limit);if(!rows.length)return <View style={s.empty}><Text style={s.emptyText}>No data available yet.</Text></View>;return <View style={s.dataCard}>{rows.map((r,i)=><View key={`${r.label}-${i}`} style={[s.dataRow,i!==rows.length-1&&s.divider]}><Text numberOfLines={2} style={s.dataLabel}>{r.label}</Text><Text numberOfLines={3} style={s.dataValue}>{r.value}</Text></View>)}</View>;}

function CompactMatches({value}){const rows=extractArray(value).map((x,i)=>normalizeFootballMatch(x,i)).filter((m)=>m?.home?.name&&m?.away?.name).slice(0,12);if(!rows.length)return <View style={s.empty}><Text style={s.emptyText}>No matches available.</Text></View>;return <View style={s.matchList}>{rows.map((m,i)=>{const has=m.homeScore!==null&&m.homeScore!==undefined&&m.awayScore!==null&&m.awayScore!==undefined;const time=m.kickoff?new Date(m.kickoff):null;const label=time&&!Number.isNaN(time.getTime())?time.toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):(m.statusCode||"");return <View key={`${m.id}-${i}`} style={[s.matchRow,i!==rows.length-1&&s.divider]}><View style={{width:70}}><Text style={s.matchDate}>{label}</Text></View><View style={{flex:1}}><Text numberOfLines={1} style={s.matchTeam}>{m.home.name}</Text><Text numberOfLines={1} style={s.matchTeam}>{m.away.name}</Text></View><View style={s.scoreCol}><Text style={s.matchScore}>{has?m.homeScore:""}</Text><Text style={s.matchScore}>{has?m.awayScore:""}</Text></View></View>;})}</View>;}

function TablePreview({value}){const arrays=[];const walk=(v,d=0)=>{if(d>6||v==null)return;if(Array.isArray(v)){if(v.length&&v.every((x)=>x&&typeof x==="object"))arrays.push(v);v.forEach((x)=>walk(x,d+1));}else if(typeof v==="object")Object.values(v).forEach((x)=>walk(x,d+1));};walk(value);const candidates=arrays.sort((a,b)=>b.length-a.length);const rows=(candidates[0]||[]).slice(0,12);if(!rows.length)return <DataRows value={value}/>;return <View style={s.table}><View style={[s.tableRow,s.tableHeader]}><Text style={s.pos}>#</Text><Text style={s.tableTeam}>TEAM</Text><Text style={s.tableNum}>P</Text><Text style={s.tableNum}>GD</Text><Text style={s.tableNum}>PTS</Text></View>{rows.map((r,i)=>{const team=r.team||r.club||r;const rank=pick(r.rank,r.position,i+1);const played=pick(r.all?.played,r.played,r.matchesPlayed,"");const gd=pick(r.goalsDiff,r.goalDifference,r.gd,"");const pts=pick(r.points,r.pts,"");return <View key={`${team?.id||team?.name||i}`} style={[s.tableRow,i!==rows.length-1&&s.divider]}><Text style={s.pos}>{rank}</Text><View style={s.tableTeamWrap}>{team?.logo?<Image source={{uri:team.logo}} style={s.smallLogo}/>:null}<Text numberOfLines={1} style={s.tableTeam}>{team?.name||r.name||"Team"}</Text></View><Text style={s.tableNum}>{played}</Text><Text style={s.tableNum}>{gd}</Text><Text style={[s.tableNum,{color:C.text,fontWeight:"900"}]}>{pts}</Text></View>;})}</View>;}

export default function NativeEntityScreenV2({type,entity,goBack}){
 const [tab,setTab]=useState("OVERVIEW");const [state,setState]=useState({loading:true,error:"",data:null});const title=entityTitle(type,entity);const tabs=tabsFor(type);
 const load=useCallback(async()=>{if(!entity?.id)return setState({loading:false,error:"Missing data ID",data:null});setState((p)=>({...p,loading:true,error:""}));try{const data=type==="competition"?await fetchCompetitionBundle(entity):type==="team"?await fetchTeamBundle(entity):await fetchPlayerBundle(entity);setState({loading:false,error:"",data});}catch(e){setState({loading:false,error:e?.message||"Could not load details",data:null});}},[type,entity?.id]);
 useEffect(()=>{load();},[load]);
 const profile=profileObject(state.data?.profile)||{};const country=pick(profile?.country?.name,profile?.country,profile?.nationality,entity?.country,"");const logo=pick(profile?.logo,profile?.photo,profile?.image,profile?.team?.logo,entity?.logo,entity?.photo,entity?.image,null);
 const overview=useMemo(()=>{if(type==="competition")return {Country:country,Season:pick(profile?.season,entity?.season),Type:pick(profile?.type,"Competition"),Name:title};if(type==="team")return {Country:country,Founded:pick(profile?.founded,profile?.team?.founded),Stadium:pick(profile?.venue?.name,profile?.stadium),Capacity:pick(profile?.venue?.capacity,profile?.capacity),Coach:pick(profile?.coach?.name,profile?.manager?.name)};return {Nationality:country,Age:pick(profile?.age,profile?.player?.age),Position:pick(profile?.position,profile?.player?.position),Number:pick(profile?.number,profile?.shirtNumber),Team:pick(profile?.team?.name,profile?.club?.name)};},[type,profile,country,title,entity]);
 const value=tab==="MATCHES"?state.data?.matches:tab==="TABLE"?state.data?.standings:tab==="TEAMS"?state.data?.teams:tab==="SCORERS"?state.data?.scorers:tab==="SQUAD"?state.data?.squad:tab==="STATS"?state.data?.stats:tab==="TRANSFERS"?state.data?.transfers:tab==="TROPHIES"?state.data?.trophies:tab==="SIDELINED"?state.data?.sidelined:overview;
 return <View style={s.screen}><View style={s.header}><Pressable onPress={goBack} hitSlop={10}><Ionicons name="chevron-back" size={27} color={C.text}/></Pressable><Text style={s.headerTitle}>{type==="competition"?"Competition":type==="team"?"Team":"Player"}</Text><Ionicons name="star-outline" size={23} color={C.muted}/></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.hero}><Logo uri={logo}/><Text style={s.title}>{title}</Text>{country?<Text style={s.country}>{country}</Text>:null}<Text style={s.type}>{String(type).toUpperCase()}</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{tabs.map((x)=><Pressable key={x} style={[s.tab,tab===x&&s.tabOn]} onPress={()=>setTab(x)}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</ScrollView>{state.loading&&!state.data?<View style={s.loading}><ActivityIndicator color={C.red}/><Text style={s.emptyText}>Updating {type} data…</Text></View>:null}{state.error?<Text style={s.error}>{state.error}</Text>:null}{tab==="OVERVIEW"?<><DataRows value={overview}/>{type==="competition"&&state.data?.matches?<><Text style={s.section}>NEXT / RECENT MATCHES</Text><CompactMatches value={state.data.matches}/></>:null}{type==="team"&&state.data?.matches?<><Text style={s.section}>RECENT MATCHES</Text><CompactMatches value={state.data.matches}/></>:null}</>:tab==="MATCHES"?<CompactMatches value={value}/>:tab==="TABLE"?<TablePreview value={value}/>:<DataRows value={value}/>}</ScrollView></View>;
}

const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},header:{minHeight:62,paddingHorizontal:15,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:C.border2},headerTitle:{flex:1,textAlign:"center",fontSize:13,fontWeight:"800",color:C.text},content:{padding:14,paddingBottom:38},hero:{backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:13,padding:18,alignItems:"center"},logoFallback:{backgroundColor:C.card2,alignItems:"center",justifyContent:"center"},title:{fontSize:20,fontWeight:"900",color:C.text,textAlign:"center",marginTop:9},country:{fontSize:10,color:C.muted,marginTop:4},type:{fontSize:8.5,fontWeight:"900",letterSpacing:1.2,color:C.red,marginTop:7},tabs:{gap:5,paddingVertical:11},tab:{minWidth:82,height:36,borderRadius:8,backgroundColor:C.card,alignItems:"center",justifyContent:"center",paddingHorizontal:10},tabOn:{backgroundColor:C.redSoft,borderWidth:1,borderColor:"rgba(243,38,45,.25)"},tabText:{fontSize:8.7,fontWeight:"900",color:C.muted},tabTextOn:{color:C.red},loading:{minHeight:80,alignItems:"center",justifyContent:"center",gap:7},empty:{minHeight:100,backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:10,alignItems:"center",justifyContent:"center",padding:16},emptyText:{fontSize:9.6,color:C.muted,textAlign:"center"},error:{fontSize:9.5,color:C.red,textAlign:"center",marginBottom:8},section:{fontSize:10.5,fontWeight:"900",color:C.text2,marginTop:15,marginBottom:7},dataCard:{backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:10,overflow:"hidden"},dataRow:{minHeight:43,paddingHorizontal:11,paddingVertical:8,flexDirection:"row",justifyContent:"space-between",gap:12},dataLabel:{width:"43%",fontSize:9.5,color:C.muted,textTransform:"capitalize"},dataValue:{width:"53%",fontSize:10,color:C.text2,textAlign:"right"},divider:{borderBottomWidth:1,borderBottomColor:C.border2},matchList:{backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:10,overflow:"hidden"},matchRow:{minHeight:58,paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:8},matchDate:{fontSize:8.7,color:C.muted},matchTeam:{fontSize:10.5,color:C.text2,lineHeight:19},scoreCol:{width:24},matchScore:{fontSize:11,fontWeight:"900",color:C.text,lineHeight:19,textAlign:"right"},table:{backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:10,overflow:"hidden"},tableHeader:{backgroundColor:"#151515"},tableRow:{minHeight:42,paddingHorizontal:9,flexDirection:"row",alignItems:"center",gap:6},pos:{width:24,fontSize:9.5,fontWeight:"800",color:C.text2},tableTeamWrap:{flex:1,flexDirection:"row",alignItems:"center",gap:6},tableTeam:{flex:1,fontSize:9.8,fontWeight:"700",color:C.text2},smallLogo:{width:20,height:20},tableNum:{width:30,fontSize:9.2,color:C.text2,textAlign:"center"}});
