import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { getAuthStatus, MST_SITE_URL } from "../services/accountApi";
import {
  getNotifications,
  getNotificationPreferences,
  markAllNotificationsRead,
  markNotificationsRead,
  normalizeNotifications,
  normalizeNotificationPreferences,
  notificationUnreadCount,
  saveNotificationPreferences,
} from "../services/notificationApi";

const C={bg:"#080A0C",card:"#111416",card2:"#15191C",border:"#24292D",border2:"#1D2226",red:"#F3262D",redSoft:"rgba(243,38,45,.14)",text:"#FFFFFF",text2:"#D0D2D4",muted:"#92979B",muted2:"#666D72",green:"#31C674"};
function Header({goBack,unread,onReadAll,busy}){return <View style={s.header}><Pressable hitSlop={10} onPress={goBack}><Ionicons name="chevron-back" size={27} color={C.text}/></Pressable><View style={s.headerCopy}><Text style={s.title}>Notifications</Text><Text style={s.subtitle}>{unread?`${unread} unread · MST account inbox`:"MST account inbox"}</Text></View>{unread?<Pressable disabled={busy} hitSlop={8} onPress={onReadAll}><Text style={s.readAll}>{busy?"SAVING":"READ ALL"}</Text></Pressable>:<View style={{width:52}}/>}</View>;}
function Empty({icon,title,text,action,actionText}){return <View style={s.empty}><Ionicons name={icon} size={30} color={C.muted}/><Text style={s.emptyTitle}>{title}</Text>{text?<Text style={s.emptyText}>{text}</Text>:null}{action?<Pressable style={s.primary} onPress={action}><Text style={s.primaryText}>{actionText}</Text></Pressable>:null}</View>;}
function ToggleRow({icon,title,subtitle,value,onChange,disabled}){return <Pressable disabled={disabled} style={s.toggleRow} onPress={()=>onChange(!value)}><View style={s.rowIcon}><Ionicons name={icon} size={20} color={C.text2}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{subtitle}</Text></View><View style={[s.toggle,value&&s.toggleOn,disabled&&{opacity:.55}]}><View style={[s.knob,value&&s.knobOn]}/></View></Pressable>;}
function timeLabel(value){if(!value)return"";const d=new Date(value);if(Number.isNaN(d.getTime()))return"";const minutes=Math.max(0,Math.floor((Date.now()-d.getTime())/60000));if(minutes<1)return"Just now";if(minutes<60)return`${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours}h ago`;return`${Math.floor(hours/24)}d ago`;}
function notificationIcon(type){if(type==="match_live"||type==="match_score"||type==="match_final")return"football-outline";if(type==="favorite_article")return"star-outline";return"newspaper-outline";}

export default function NotificationsScreenV2({goBack,openAccount,openMatch}){
  const[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[authenticated,setAuthenticated]=useState(false),[items,setItems]=useState([]),[unread,setUnread]=useState(0),[prefs,setPrefs]=useState({articleAlerts:true,favoriteAlerts:true,matchKickoff:true,matchGoals:true,matchFinal:true,browserAlerts:false}),[saving,setSaving]=useState(false),[reading,setReading]=useState(""),[error,setError]=useState("");
  const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError("");try{const auth=await getAuthStatus();setAuthenticated(Boolean(auth.authenticated));if(!auth.authenticated){setItems([]);setUnread(0);return;}const[feed,prefPayload]=await Promise.all([getNotifications({sync:true,limit:60}),getNotificationPreferences()]);setItems(normalizeNotifications(feed));setUnread(notificationUnreadCount(feed));setPrefs(normalizeNotificationPreferences(prefPayload));}catch(e){setError(e?.message||"Could not load notifications.");}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{load(false);},[load]);
  const updatePref=async(key,value)=>{const previous=prefs,next={...prefs,[key]:value};setPrefs(next);setSaving(true);setError("");try{const payload=await saveNotificationPreferences(next);setPrefs(normalizeNotificationPreferences(payload));}catch(e){setPrefs(previous);setError(e?.message||"Could not save notification preference.");}finally{setSaving(false);}};
  const readAll=async()=>{if(!unread||saving)return;setSaving(true);setError("");try{const payload=await markAllNotificationsRead();setItems(normalizeNotifications(payload));setUnread(notificationUnreadCount(payload));}catch(e){setError(e?.message||"Could not mark notifications as read.");}finally{setSaving(false);}};
  const openItem=async(item)=>{if(!item?.id||reading)return;setReading(String(item.id));setError("");try{if(!item.read){const payload=await markNotificationsRead([item.id]);setItems(normalizeNotifications(payload));setUnread(notificationUnreadCount(payload));}const href=String(item.href||"");const match=href.match(/^\/match\/(\d+)/);if(match){openMatch?.({id:match[1]});return;}if(href){const url=/^https?:\/\//i.test(href)?href:`${MST_SITE_URL}${href.startsWith("/")?href:`/${href}`}`;await Linking.openURL(url);}}catch(e){setError(e?.message||"Could not open notification.");}finally{setReading("");}};
  return <View style={s.screen}><Header goBack={goBack} unread={unread} onReadAll={readAll} busy={saving}/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={C.red} colors={[C.red]}/>}>
    {loading?<View style={s.loading}><ActivityIndicator color={C.red}/><Text style={s.emptyText}>Loading notifications…</Text></View>:null}
    {!loading&&!authenticated?<Empty icon="person-circle-outline" title="Sign in for MST notifications" text="Your news and favorite-match inbox follows your MST account across website and app." action={openAccount} actionText="SIGN IN"/>:null}
    {error?<Text style={s.error}>{error}</Text>:null}
    {!loading&&authenticated?<><Text style={s.section}>ACCOUNT ALERTS</Text><View style={s.card}><ToggleRow icon="newspaper-outline" title="Articles" subtitle="New MST articles in your account inbox" value={prefs.articleAlerts} onChange={(v)=>updatePref("articleAlerts",v)} disabled={saving}/><ToggleRow icon="star-outline" title="Favorite news" subtitle="Articles related to favorite teams and competitions" value={prefs.favoriteAlerts} onChange={(v)=>updatePref("favoriteAlerts",v)} disabled={saving}/><ToggleRow icon="play-circle-outline" title="Favorite match kickoff" subtitle="When a favorite team or competition goes live" value={prefs.matchKickoff} onChange={(v)=>updatePref("matchKickoff",v)} disabled={saving}/><ToggleRow icon="football-outline" title="Favorite match goals" subtitle="Score changes for favorite matches" value={prefs.matchGoals} onChange={(v)=>updatePref("matchGoals",v)} disabled={saving}/><ToggleRow icon="checkmark-circle-outline" title="Favorite match full-time" subtitle="Final scores for favorite matches" value={prefs.matchFinal} onChange={(v)=>updatePref("matchFinal",v)} disabled={saving}/><ToggleRow icon="desktop-outline" title="Website browser alerts" subtitle="Browser notification preference for myanmarsportstalk.com" value={prefs.browserAlerts} onChange={(v)=>updatePref("browserAlerts",v)} disabled={saving}/></View><View style={s.sectionHead}><Text style={s.section}>RECENT</Text><Text style={s.count}>{items.length} items</Text></View>{items.length?<View style={s.card}>{items.map((item,index)=><Pressable key={String(item.id)} disabled={reading===String(item.id)} style={[s.notification,index!==items.length-1&&s.divider,!item.read&&s.unreadRow]} onPress={()=>openItem(item)}><View style={s.notificationIcon}><Ionicons name={notificationIcon(item.type)} size={18} color={!item.read?C.red:C.muted}/></View><View style={{flex:1,minWidth:0}}><View style={s.notificationTitleRow}><Text numberOfLines={2} style={[s.notificationTitle,!item.read&&{color:C.text}]}>{item.title}</Text>{!item.read?<View style={s.dot}/>:null}</View>{item.body?<Text numberOfLines={3} style={s.notificationBody}>{item.body}</Text>:null}<Text style={s.notificationTime}>{timeLabel(item.createdAt)}</Text></View>{reading===String(item.id)?<ActivityIndicator size="small" color={C.red}/>:<Ionicons name="chevron-forward" size={17} color={C.muted}/>}</Pressable>)}</View>:<Empty icon="notifications-outline" title="No notifications yet" text="New MST article and favorite-match updates will appear here."/>}</>:null}
  </ScrollView></View>;
}

const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},header:{minHeight:64,paddingHorizontal:14,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:C.border2},headerCopy:{flex:1,paddingHorizontal:11},title:{fontSize:16,fontWeight:"900",color:C.text},subtitle:{fontSize:9.2,color:C.muted,marginTop:2},readAll:{fontSize:8.5,fontWeight:"900",color:C.red},content:{padding:14,paddingBottom:40},loading:{minHeight:130,alignItems:"center",justifyContent:"center",gap:8},section:{fontSize:10.5,fontWeight:"900",color:C.text2,marginTop:10,marginBottom:8},sectionHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},count:{fontSize:9,color:C.muted},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:11,overflow:"hidden",marginBottom:8},toggleRow:{minHeight:63,paddingHorizontal:11,paddingVertical:8,flexDirection:"row",alignItems:"center",gap:9,borderBottomWidth:1,borderBottomColor:C.border2},rowIcon:{width:34,height:34,borderRadius:9,backgroundColor:C.card2,alignItems:"center",justifyContent:"center"},rowTitle:{fontSize:11.6,fontWeight:"800",color:C.text2},rowSub:{fontSize:8.8,color:C.muted,marginTop:3,lineHeight:13},toggle:{width:42,height:24,borderRadius:12,backgroundColor:C.border,justifyContent:"center",paddingHorizontal:3},toggleOn:{backgroundColor:C.red},knob:{width:18,height:18,borderRadius:9,backgroundColor:C.text},knobOn:{alignSelf:"flex-end"},notification:{minHeight:80,paddingHorizontal:11,paddingVertical:10,flexDirection:"row",alignItems:"center",gap:9},unreadRow:{backgroundColor:"rgba(243,38,45,.035)"},divider:{borderBottomWidth:1,borderBottomColor:C.border2},notificationIcon:{width:34,height:34,borderRadius:17,backgroundColor:C.card2,alignItems:"center",justifyContent:"center"},notificationTitleRow:{flexDirection:"row",alignItems:"flex-start",gap:6},notificationTitle:{flex:1,fontSize:11.5,fontWeight:"800",color:C.text2,lineHeight:15},dot:{width:6,height:6,borderRadius:3,backgroundColor:C.red,marginTop:4},notificationBody:{fontSize:9.4,color:C.muted,lineHeight:13,marginTop:3},notificationTime:{fontSize:8.3,color:C.muted2,marginTop:4},empty:{minHeight:150,backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:11,padding:17,alignItems:"center",justifyContent:"center",gap:7},emptyTitle:{fontSize:13,fontWeight:"900",color:C.text,textAlign:"center"},emptyText:{fontSize:9.7,color:C.muted,textAlign:"center",lineHeight:14,maxWidth:280},primary:{height:38,borderRadius:8,backgroundColor:C.red,paddingHorizontal:15,alignItems:"center",justifyContent:"center",marginTop:3},primaryText:{fontSize:9,fontWeight:"900",color:C.text},error:{fontSize:9.5,color:C.red,backgroundColor:C.redSoft,borderRadius:8,padding:9,textAlign:"center",marginBottom:7}});
