import React, { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { fetchFootballMatches, isLiveMatch, offsetDateString } from "../services/footballApi";

const C={bg:"#080A0C",card:"#111416",border:"#24292D",border2:"#1D2226",red:"#F3262D",redSoft:"rgba(243,38,45,0.14)",text:"#FFFFFF",text2:"#D0D2D4",muted:"#92979B"};

function useMatches(date){
  const [state,setState]=useState({loading:true,refreshing:false,error:"",matches:[]});
  const load=useCallback(async(refresh=false)=>{setState(p=>({...p,loading:!refresh&&!p.matches.length,refreshing:refresh,error:""}));try{const r=await fetchFootballMatches({date});setState({loading:false,refreshing:false,error:"",matches:r.matches||[]});}catch(e){setState(p=>({...p,loading:false,refreshing:false,error:e?.message||"Could not load matches."}));}},[date]);
  useEffect(()=>{load();},[load]);
  return {...state,reload:()=>load(false),refresh:()=>load(true)};
}

function MatchRow({match,onOpen}){
  const live=isLiveMatch(match); const has=match.homeScore!==null&&match.homeScore!==undefined&&match.awayScore!==null&&match.awayScore!==undefined;
  return <Pressable style={s.card} onPress={()=>onOpen?.(match)}><View style={s.cardTop}><Text numberOfLines={1} style={s.comp}>{match.competition}</Text><Text style={[s.time,live&&{color:C.red,fontWeight:"800"}]}>{live?match.minute:match.statusCode==="FT"?"FT":match.minute}</Text></View><View style={s.teamRow}><View style={{flex:1}}><Text numberOfLines={1} style={s.team}>{match.home?.name}</Text><Text numberOfLines={1} style={s.team}>{match.away?.name}</Text></View><View style={s.scoreBox}><Text style={s.score}>{has?match.homeScore:"-"}</Text><Text style={s.score}>{has?match.awayScore:"-"}</Text></View></View></Pressable>;
}

export default function QuickScoresScreen({openMatch}){
  const [tab,setTab]=useState("TODAY"); const offset=tab==="YESTERDAY"?-1:tab==="TOMORROW"?1:0; const date=offsetDateString(offset); const api=useMatches(date);
  return <View style={s.screen}><View style={s.header}><View><Text style={s.title}>Scores</Text><Text style={s.sub}>Real MST football data</Text></View><Ionicons name="calendar-outline" size={27} color={C.text}/></View><View style={s.tabs}>{["YESTERDAY","TODAY","TOMORROW"].map(x=><Pressable key={x} style={[s.tab,tab===x&&s.tabOn]} onPress={()=>setTab(x)}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={api.refreshing} onRefresh={api.refresh} tintColor={C.red} colors={[C.red]}/>}><View style={s.section}><Text style={s.sectionTitle}>{tab==="TODAY"?"TODAY'S MATCHES":tab}</Text><Text style={s.count}>{api.matches.length} matches</Text></View>{api.loading&&!api.matches.length?<View style={s.state}><ActivityIndicator color={C.red}/><Text style={s.stateText}>Loading matches…</Text></View>:null}{api.error?<View style={s.state}><Ionicons name="cloud-offline-outline" size={25} color={C.muted}/><Text style={s.stateText}>{api.error}</Text><Pressable style={s.retry} onPress={api.reload}><Text style={s.retryText}>RETRY</Text></Pressable></View>:null}{!api.loading&&!api.error&&!api.matches.length?<View style={s.state}><Ionicons name="football-outline" size={25} color={C.muted}/><Text style={s.stateText}>No matches found for this day.</Text></View>:null}{api.matches.map(m=><MatchRow key={m.id} match={m} onOpen={openMatch}/>)}<View style={{height:30}}/></ScrollView></View>;
}

const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},header:{minHeight:70,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:C.border2},title:{fontSize:22,fontWeight:"800",color:C.text},sub:{fontSize:10.5,color:C.muted,marginTop:3},tabs:{flexDirection:"row",padding:8,gap:7,borderBottomWidth:1,borderBottomColor:C.border2},tab:{flex:1,paddingVertical:9,borderRadius:8,alignItems:"center"},tabOn:{backgroundColor:C.redSoft},tabText:{fontSize:10,fontWeight:"700",color:C.muted},tabTextOn:{color:C.red},content:{paddingHorizontal:16,paddingTop:10},section:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:9},sectionTitle:{fontSize:12,fontWeight:"900",color:C.text2},count:{fontSize:10.5,color:C.muted},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:11,padding:12,marginBottom:8},cardTop:{flexDirection:"row",justifyContent:"space-between",gap:8},comp:{flex:1,fontSize:10,fontWeight:"800",color:C.text2},time:{fontSize:10,color:C.muted},teamRow:{flexDirection:"row",alignItems:"center",marginTop:9},team:{fontSize:12.5,color:C.text,marginVertical:3},scoreBox:{width:36,alignItems:"flex-end"},score:{fontSize:14,fontWeight:"900",color:C.text,marginVertical:2},state:{minHeight:120,backgroundColor:C.card,borderWidth:1,borderColor:C.border2,borderRadius:11,alignItems:"center",justifyContent:"center",gap:8,padding:15},stateText:{fontSize:10.5,color:C.muted,textAlign:"center"},retry:{backgroundColor:C.red,borderRadius:7,paddingHorizontal:16,paddingVertical:8},retryText:{fontSize:10,fontWeight:"900",color:C.text}});
