import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { getAuthStatus } from "../services/accountApi";
import { fetchFastFootballMatches, peekFastFootballMatches, prefetchFastFootballMatches } from "../services/fastFootballApi";
import {
  applyTipster,
  CREDIT_REFERENCE,
  getTips,
  getTipsMe,
  getTipsters,
  publishTip,
  requestTipsterPayout,
  TIP_PRICES,
  TIPSTER_LEVEL_FALLBACK,
  unlockTip,
} from "../services/tipsApi";

const C={bg:"#07090B",panel:"#0D1013",card:"#111519",card2:"#151A1F",border:"#20262C",border2:"#181D22",red:"#F32735",redSoft:"rgba(243,39,53,.12)",text:"#F7F8F9",text2:"#D7DBDF",muted:"#858C93",muted2:"#5F666D",green:"#22C777",gold:"#F4C84D",blue:"#43A9E8"};
const TABS=["TIPS","TIPSTERS","CREDITS","TIPSTER"];
const MARKETS={
  "1x2":{label:"MATCH RESULT", selections:[["home","HOME"],["draw","DRAW"],["away","AWAY"]]},
  ou25:{label:"TOTAL GOALS 2.5", selections:[["over","OVER 2.5"],["under","UNDER 2.5"]]},
  btts:{label:"BOTH TEAMS TO SCORE", selections:[["yes","YES"],["no","NO"]]},
};

const tx=(my,en,myText)=>my?myText:en;
function bangkokDate(offset=0){const date=new Date(Date.now()+offset*86400000);try{const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${v.year}-${v.month}-${v.day}`;}catch(_){return date.toISOString().slice(0,10);}}
function fmtDate(value){if(!value)return"";const d=new Date(value);return Number.isNaN(d.getTime())?"":d.toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});}
function Logo({uri,size=34}){return uri?<Image source={{uri}} resizeMode="contain" fadeDuration={0} style={{width:size,height:size}}/>:<View style={[s.logoFallback,{width:size,height:size,borderRadius:size/2}]}><Ionicons name="football-outline" size={size*.5} color={C.muted}/></View>;}
function levelName(level,me){return me?.economy?.levels?.[level]?.name||TIPSTER_LEVEL_FALLBACK[level]?.name||`Level ${level}`;}
function marketLabel(market,selection){return MARKETS[market]?.selections?.find(([id])=>id===selection)?.[1]||selection||"";}
function streakTone(streak){return String(streak||"").startsWith("W")?C.green:String(streak||"").startsWith("L")?C.red:C.muted;}

function LevelBadge({level=1,name}){return <View style={[s.levelBadge,level>=5&&{borderColor:C.gold}]}><Ionicons name={level>=4?"diamond-outline":"shield-checkmark-outline"} size={11} color={level>=5?C.gold:C.red}/><Text style={[s.levelText,level>=5&&{color:C.gold}]}>LV.{level} {String(name||"").toUpperCase()}</Text></View>;}

function TipCard({tip,onUnlock,unlocking,authenticated,openAccount,my}){
  const stats=tip?.tipster||{};const locked=Boolean(tip?.locked);const result=tip?.result;
  return <View style={s.tipCard}>
    <View style={s.tipTop}><View style={{flex:1}}><Text numberOfLines={1} style={s.competition}>{tip.competition||"Football"}</Text><Text style={s.kickoff}>{fmtDate(tip.kickoff)}</Text></View>{result?<View style={[s.resultBadge,result==="win"?s.resultWin:result==="loss"?s.resultLoss:s.resultVoid]}><Text style={s.resultText}>{String(result).toUpperCase()}</Text></View>:null}</View>
    <View style={s.matchRow}><Text numberOfLines={1} style={s.matchTeam}>{tip.homeTeam}</Text><Text style={s.vs}>VS</Text><Text numberOfLines={1} style={[s.matchTeam,{textAlign:"right"}]}>{tip.awayTeam}</Text></View>
    <View style={s.tipsterRow}><View style={s.tipsterAvatar}><Ionicons name="person" size={17} color={C.text2}/></View><View style={{flex:1}}><Text numberOfLines={1} style={s.tipsterName}>{stats.displayName||"MST Tipster"}</Text><View style={s.inline}><LevelBadge level={Number(stats.level||1)} name={levelName(Number(stats.level||1))}/>{stats.currentStreak?<Text style={[s.streak,{color:streakTone(stats.currentStreak)}]}>{stats.currentStreak}</Text>:null}</View></View><View style={s.winBox}><Text style={s.winNum}>{Number(stats.winRate||0).toFixed(1)}%</Text><Text style={s.winLabel}>WIN RATE</Text></View></View>
    <View style={s.tipMeta}><View style={s.metaItem}><Text style={s.metaLabel}>CONFIDENCE</Text><Text style={s.metaValue}>{tip.confidence}/10</Text></View><View style={s.metaItem}><Text style={s.metaLabel}>RECORD</Text><Text style={s.metaValue}>{stats.wins||0}W · {stats.losses||0}L</Text></View><View style={s.metaItem}><Text style={s.metaLabel}>PRICE</Text><Text style={[s.metaValue,{color:C.gold}]}>{tip.priceCredits} CR</Text></View></View>
    {locked?<View style={s.lockedBox}><Ionicons name="lock-closed" size={20} color={C.muted}/><View style={{flex:1}}><Text style={s.lockedTitle}>{tx(my,"Premium tip locked","ပရီမီယမ် tip ပိတ်ထားသည်")}</Text><Text style={s.lockedText}>{tx(my,"Unlock to see the pick and Tipster analysis.","ရွေးချယ်မှုနှင့် Tipster သုံးသပ်ချက်ကြည့်ရန် ဖွင့်ပါ။")}</Text></View><Pressable disabled={unlocking} style={s.unlockButton} onPress={()=>authenticated?onUnlock?.(tip):openAccount?.()}>{unlocking?<ActivityIndicator size="small" color={C.text}/>:<><Text style={s.unlockPrice}>{tip.priceCredits}</Text><Text style={s.unlockSmall}>CREDITS</Text></>}</Pressable></View>:<View style={s.revealed}><View style={s.pickHead}><Text style={s.marketName}>{MARKETS[tip.market]?.label||String(tip.market||"").toUpperCase()}</Text><Text style={s.pick}>{marketLabel(tip.market,tip.selection)}</Text></View><Text style={s.analysis}>{tip.analysis}</Text></View>}
    <View style={s.disclaimer}><Ionicons name="information-circle-outline" size={12} color={C.muted}/><Text style={s.disclaimerText}>{tx(my,"Football analysis only · results are never guaranteed.","ဘောလုံးသုံးသပ်ချက်သာ ဖြစ်ပြီး ရလဒ်အာမခံမရှိပါ။")}</Text></View>
  </View>;
}

function TipsterCard({item}){const stats=item.stats||{};return <View style={s.personCard}><View style={s.personAvatar}><Ionicons name="person" size={22} color={C.text2}/></View><View style={{flex:1}}><Text style={s.personName}>{item.displayName||"MST Tipster"}</Text><View style={s.inline}><LevelBadge level={item.level} name={item.name}/>{stats.currentStreak?<Text style={[s.streak,{color:streakTone(stats.currentStreak)}]}>{stats.currentStreak}</Text>:null}</View><Text numberOfLines={2} style={s.personBio}>{item.bio||item.specialties||"Verified MST Tipster"}</Text></View><View style={s.personStats}><Text style={s.personRate}>{Number(stats.winRate||0).toFixed(1)}%</Text><Text style={s.personMini}>{stats.wins||0}W · {stats.losses||0}L</Text><Text style={s.personMini}>{stats.totalTips||0} tips</Text></View></View>;}

function CreditPanel({me,authenticated,openAccount,my}){
  const balance=me?.wallet?.balance??0;
  const packs=[[100,250],[220,500],[480,1000],[1000,2000]];
  return <>
    <View style={s.walletHero}><View><Text style={s.eyebrow}>MST CREDITS</Text><Text style={s.walletNumber}>{Number(balance).toLocaleString()}</Text><Text style={s.walletSub}>{tx(my,"Available balance","လက်ကျန် Credits")}</Text></View><View style={s.creditCoin}><Text style={s.coinText}>MST</Text></View></View>
    {!authenticated?<Pressable style={s.primary} onPress={openAccount}><Text style={s.primaryText}>{tx(my,"SIGN IN","အကောင့်ဝင်မည်")}</Text></Pressable>:null}
    <View style={s.infoCard}><Text style={s.infoTitle}>{tx(my,"Reference value","ရည်ညွှန်းတန်ဖိုး")}</Text><Text style={s.reference}>{CREDIT_REFERENCE.credits} Credits = ฿{CREDIT_REFERENCE.thb}</Text><Text style={s.infoText}>{tx(my,"Tips are always priced in MST Credits. Store checkout will show the supported local currency for the buyer.","Tips များကို MST Credits ဖြင့်သာ ဈေးနှုန်းသတ်မှတ်မည်။ Store checkout တွင် ဝယ်သူအတွက် support လုပ်သော local currency ကိုပြမည်။")}</Text></View>
    <Text style={s.sectionTitle}>{tx(my,"Credit packs","Credit packs")}</Text>
    <View style={s.packGrid}>{packs.map(([credits,thb])=><View key={credits} style={s.pack}><Text style={s.packCredits}>{credits}</Text><Text style={s.packLabel}>CREDITS</Text><Text style={s.packPrice}>≈ ฿{thb}</Text></View>)}</View>
    <View style={s.pendingCard}><Ionicons name="card-outline" size={19} color={C.gold}/><View style={{flex:1}}><Text style={s.pendingTitle}>{tx(my,"Store billing connection","Store billing ချိတ်ဆက်မှု")}</Text><Text style={s.pendingText}>{tx(my,"Credit packs are defined, but real App Store / Google Play checkout must be connected before customers can buy them.","Credit pack ဈေးနှုန်းများသတ်မှတ်ပြီးပါပြီ။ အမှန်တကယ်ဝယ်ယူရန် App Store / Google Play billing ကို release မတိုင်မီချိတ်ဆက်ရမည်။")}</Text></View></View>
  </>;
}

function ApplicationPanel({me,onApply,loading,my}){
  const [bio,setBio]=useState("");const [specialties,setSpecialties]=useState("");const [currency,setCurrency]=useState("THB");
  if(me?.tipster?.status==="pending")return <View style={s.statusCard}><Ionicons name="time-outline" size={25} color={C.gold}/><Text style={s.statusTitle}>{tx(my,"Tipster application pending","Tipster လျှောက်လွှာ စစ်ဆေးနေသည်")}</Text><Text style={s.statusText}>{tx(my,"MST admin must approve the account before paid tips can be published.","Paid tips တင်နိုင်ရန် MST admin မှ အတည်ပြုရမည်။")}</Text></View>;
  if(me?.tipster?.status==="rejected")return <View style={s.statusCard}><Ionicons name="alert-circle-outline" size={25} color={C.red}/><Text style={s.statusTitle}>{tx(my,"Application needs review","လျှောက်လွှာ ပြန်စစ်ရန်လိုသည်")}</Text><Text style={s.statusText}>{tx(my,"Update your details and apply again.","အချက်အလက်ပြင်ပြီး ပြန်လျှောက်နိုင်သည်။")}</Text><Pressable style={s.secondary}><Text style={s.secondaryText}>RE-APPLY BELOW</Text></Pressable></View>;
  return <View style={s.formCard}><Text style={s.formTitle}>{tx(my,"Apply to become a Tipster","Tipster ဖြစ်ရန် လျှောက်ထားမည်")}</Text><Text style={s.formSub}>{tx(my,"Approved Tipsters receive a level, daily publishing limit and price ceiling.","Approved Tipster များကို Level၊ တစ်နေ့ Tip limit နှင့် ဈေးနှုန်းအများဆုံး သတ်မှတ်ပေးမည်။")}</Text><Text style={s.inputLabel}>BIO / EXPERIENCE</Text><TextInput value={bio} onChangeText={setBio} multiline maxLength={600} placeholder="Football experience, approach, leagues…" placeholderTextColor={C.muted2} style={[s.input,s.multiline]}/><Text style={s.inputLabel}>SPECIALTIES</Text><TextInput value={specialties} onChangeText={setSpecialties} maxLength={300} placeholder="Premier League, UCL, totals…" placeholderTextColor={C.muted2} style={s.input}/><Text style={s.inputLabel}>PREFERRED PAYOUT CURRENCY</Text><TextInput value={currency} onChangeText={(v)=>setCurrency(v.toUpperCase().replace(/[^A-Z]/g,"").slice(0,10))} placeholder="THB" placeholderTextColor={C.muted2} style={s.input}/><Pressable disabled={loading||bio.trim().length<20} style={[s.primary,(loading||bio.trim().length<20)&&s.disabled]} onPress={()=>onApply?.({bio,specialties,payoutCurrency:currency||"THB"})}>{loading?<ActivityIndicator color={C.text}/>:<Text style={s.primaryText}>SUBMIT TIPSTER APPLICATION</Text>}</Pressable></View>;
}

function TipsterDashboard({me,matches,onPublish,onPayout,loading,my}){
  const tipster=me?.tipster||{};const earnings=me?.earnings||{};const [matchId,setMatchId]=useState("");const selected=useMemo(()=>matches.find(m=>String(m.id)===String(matchId))||matches[0]||null,[matches,matchId]);
  const [market,setMarket]=useState("1x2"),[selection,setSelection]=useState("home"),[price,setPrice]=useState(5),[confidence,setConfidence]=useState(7),[analysis,setAnalysis]=useState("");const [payoutCredits,setPayoutCredits]=useState(""),[currency,setCurrency]=useState(tipster.payoutCurrency||"THB");
  useEffect(()=>{if(selected&&!matchId)setMatchId(String(selected.id));},[selected,matchId]);
  useEffect(()=>{const first=MARKETS[market]?.selections?.[0]?.[0];if(first)setSelection(first);},[market]);
  const allowed=TIP_PRICES.filter(v=>v<=Number(tipster.maxPrice||5));
  useEffect(()=>{if(!allowed.includes(price))setPrice(allowed[0]||5);},[tipster.maxPrice]);
  const canPublish=selected&&analysis.trim().length>=20&&!loading;
  return <>
    <View style={s.dashboardHero}><View style={{flex:1}}><LevelBadge level={tipster.level} name={tipster.name}/><Text style={s.dashboardTitle}>{tipster.name} Tipster</Text><Text style={s.dashboardSub}>{tipster.dailyUsed||0} / {tipster.dailyTips||1} tips used today · Max {tipster.maxPrice||5} Credits</Text></View><View style={s.bigRate}><Text style={s.bigRateNum}>{Number(tipster.stats?.winRate||0).toFixed(1)}%</Text><Text style={s.bigRateLabel}>WIN RATE</Text></View></View>
    <View style={s.statsGrid}><View style={s.stat}><Text style={s.statLabel}>AVAILABLE</Text><Text style={s.statNum}>{earnings.availableCredits||0}</Text><Text style={s.statSub}>earned credits</Text></View><View style={s.stat}><Text style={s.statLabel}>PENDING PAYOUT</Text><Text style={s.statNum}>{earnings.pendingPayoutCredits||0}</Text><Text style={s.statSub}>credits</Text></View><View style={s.stat}><Text style={s.statLabel}>STREAK</Text><Text style={[s.statNum,{color:streakTone(tipster.stats?.currentStreak)}]}>{tipster.stats?.currentStreak||"—"}</Text><Text style={s.statSub}>{tipster.stats?.wins||0}W · {tipster.stats?.losses||0}L</Text></View></View>

    <View style={s.formCard}><Text style={s.formTitle}>{tx(my,"Publish a premium tip","Premium tip တင်မည်")}</Text><Text style={s.inputLabel}>MATCH</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.matchPicker}>{matches.slice(0,24).map(m=><Pressable key={m.id} style={[s.matchPick,String(selected?.id)===String(m.id)&&s.matchPickOn]} onPress={()=>setMatchId(String(m.id))}><Text numberOfLines={1} style={s.matchPickLeague}>{m.competition}</Text><Text numberOfLines={1} style={s.matchPickTeam}>{m.home?.name}</Text><Text numberOfLines={1} style={s.matchPickTeam}>{m.away?.name}</Text><Text style={s.matchPickTime}>{fmtDate(m.kickoff)}</Text></Pressable>)}</ScrollView>{!matches.length?<Text style={s.empty}>No upcoming matches loaded.</Text>:null}
      <Text style={s.inputLabel}>MARKET</Text><View style={s.chips}>{Object.entries(MARKETS).map(([id,v])=><Pressable key={id} style={[s.chip,market===id&&s.chipOn]} onPress={()=>setMarket(id)}><Text style={[s.chipText,market===id&&s.chipTextOn]}>{v.label}</Text></Pressable>)}</View>
      <Text style={s.inputLabel}>SELECTION</Text><View style={s.chips}>{MARKETS[market].selections.map(([id,label])=><Pressable key={id} style={[s.chip,selection===id&&s.chipOn]} onPress={()=>setSelection(id)}><Text style={[s.chipText,selection===id&&s.chipTextOn]}>{label}</Text></Pressable>)}</View>
      <Text style={s.inputLabel}>PRICE · LEVEL {tipster.level} MAX {tipster.maxPrice} CREDITS</Text><View style={s.chips}>{allowed.map(v=><Pressable key={v} style={[s.priceChip,price===v&&s.priceChipOn]} onPress={()=>setPrice(v)}><Text style={[s.priceChipText,price===v&&{color:C.gold}]}>{v} CR</Text></Pressable>)}</View>
      <Text style={s.inputLabel}>CONFIDENCE</Text><View style={s.chips}>{[6,7,8,9,10].map(v=><Pressable key={v} style={[s.chip,confidence===v&&s.chipOn]} onPress={()=>setConfidence(v)}><Text style={[s.chipText,confidence===v&&s.chipTextOn]}>{v}/10</Text></Pressable>)}</View>
      <Text style={s.inputLabel}>ANALYSIS</Text><TextInput value={analysis} onChangeText={setAnalysis} multiline maxLength={1500} placeholder="Explain why you chose this market. No guaranteed-win claims." placeholderTextColor={C.muted2} style={[s.input,s.analysisInput]}/>
      <View style={s.ruleBox}><Ionicons name="lock-closed-outline" size={15} color={C.red}/><Text style={s.ruleText}>One official tip per match. Once kickoff starts, the tip cannot be changed or deleted. Losing tips stay in the verified record.</Text></View>
      <Pressable disabled={!canPublish} style={[s.primary,!canPublish&&s.disabled]} onPress={()=>onPublish?.({matchId:selected.id,competition:selected.competition,homeTeam:selected.home?.name,awayTeam:selected.away?.name,kickoff:selected.kickoff,market,selection,priceCredits:price,confidence,analysis})}>{loading?<ActivityIndicator color={C.text}/>:<Text style={s.primaryText}>PUBLISH VERIFIED TIP</Text>}</Pressable>
    </View>

    <View style={s.formCard}><Text style={s.formTitle}>{tx(my,"Withdraw Tipster earnings","Tipster ဝင်ငွေထုတ်ယူရန်")}</Text><Text style={s.formSub}>70% Tipster / 30% MST · Minimum {earnings.payoutMinimumCredits||800} earned credits. Taxes/withholding may apply where required.</Text><View style={s.payoutRow}><TextInput value={payoutCredits} onChangeText={(v)=>setPayoutCredits(v.replace(/[^0-9]/g,"").slice(0,8))} keyboardType="number-pad" placeholder="800" placeholderTextColor={C.muted2} style={[s.input,{flex:1,marginBottom:0}]}/><TextInput value={currency} onChangeText={(v)=>setCurrency(v.toUpperCase().replace(/[^A-Z]/g,"").slice(0,10))} placeholder="THB" placeholderTextColor={C.muted2} style={[s.input,{width:82,marginBottom:0}]}/></View><Pressable disabled={loading||Number(payoutCredits)<Number(earnings.payoutMinimumCredits||800)} style={[s.secondary,(loading||Number(payoutCredits)<Number(earnings.payoutMinimumCredits||800))&&s.disabled]} onPress={()=>onPayout?.({credits:Number(payoutCredits),currency})}><Text style={s.secondaryText}>REQUEST PAYOUT</Text></Pressable></View>
  </>;
}

export default function TipsScreen({language="my",openAccount,openMatch}){
  const my=language!=="en";const [tab,setTab]=useState("TIPS"),[auth,setAuth]=useState(false),[tips,setTips]=useState([]),[tipsters,setTipsters]=useState([]),[me,setMe]=useState(null),[matches,setMatches]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
  const loadMatches=useCallback(async(force=false)=>{const dates=[bangkokDate(0),bangkokDate(1),bangkokDate(2)];prefetchFastFootballMatches(dates);const rows=[];for(const date of dates){try{const cached=peekFastFootballMatches(date);const data=cached?.matches?.length&&!force?cached.matches:(await fetchFastFootballMatches({date,force})).matches||[];rows.push(...data);}catch(_){}}const now=Date.now();setMatches(rows.filter(m=>m.kickoff&&new Date(m.kickoff).getTime()>now).sort((a,b)=>new Date(a.kickoff)-new Date(b.kickoff)));},[]);
  const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError("");try{const a=await getAuthStatus().catch(()=>({authenticated:false}));setAuth(Boolean(a.authenticated));const [tipsData,tipsterData,meData]=await Promise.all([getTips({limit:60}).catch(()=>[]),getTipsters({limit:60}).catch(()=>[]),a.authenticated?getTipsMe().catch(()=>null):Promise.resolve(null)]);setTips(Array.isArray(tipsData)?tipsData:[]);setTipsters(Array.isArray(tipsterData)?tipsterData:[]);setMe(meData);if(meData?.tipster?.status==="approved")await loadMatches(refresh);}catch(e){setError(e?.message||"Could not load MST Tips.");}finally{setLoading(false);setRefreshing(false);}},[loadMatches]);
  useEffect(()=>{load(false);},[load]);
  const doUnlock=async(tip)=>{if(!auth){openAccount?.();return;}setBusy(`unlock:${tip.id}`);setMessage("");setError("");try{await unlockTip(tip.id);setMessage(`${tip.priceCredits} Credits used · tip unlocked.`);await load(false);}catch(e){setError(e?.message||"Could not unlock tip.");}finally{setBusy("");}};
  const doApply=async(input)=>{if(!auth){openAccount?.();return;}setBusy("apply");setError("");try{await applyTipster(input);setMessage("Tipster application submitted for MST review.");await load(false);}catch(e){setError(e?.message||"Could not submit application.");}finally{setBusy("");}};
  const doPublish=async(input)=>{setBusy("publish");setError("");try{await publishTip(input);setMessage("Verified tip published. It will lock permanently at kickoff.");await load(false);}catch(e){setError(e?.message||"Could not publish tip.");}finally{setBusy("");}};
  const doPayout=async(input)=>{setBusy("payout");setError("");try{await requestTipsterPayout(input);setMessage("Payout request submitted for MST review.");await load(false);}catch(e){setError(e?.message||"Could not request payout.");}finally{setBusy("");}};

  return <View style={s.screen}><View style={s.header}><View><Text style={s.title}>MST Tips</Text><Text style={s.subtitle}>{tx(my,"Verified football analysis marketplace","Verified ဘောလုံးသုံးသပ်ချက် marketplace")}</Text></View><View style={s.headerCoin}><Ionicons name="diamond-outline" size={17} color={C.gold}/><Text style={s.headerCoinText}>{auth?Number(me?.wallet?.balance||0).toLocaleString():"—"}</Text></View></View><View style={s.tabs}>{TABS.map(x=><Pressable key={x} style={[s.tab,tab===x&&s.tabOn]} onPress={()=>setTab(x)}><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={C.red} colors={[C.red]}/>}>
    {message?<View style={s.message}><Ionicons name="checkmark-circle-outline" size={16} color={C.green}/><Text style={s.messageText}>{message}</Text></View>:null}{error?<View style={s.errorBox}><Ionicons name="alert-circle-outline" size={16} color={C.red}/><Text style={s.errorText}>{error}</Text></View>:null}
    {loading&&!tips.length?<View style={s.loading}><ActivityIndicator color={C.red}/><Text style={s.empty}>Loading MST Tips…</Text></View>:null}
    {tab==="TIPS"?<><View style={s.marketHero}><View style={{flex:1}}><Text style={s.eyebrow}>PREMIUM FOOTBALL ANALYSIS</Text><Text style={s.marketHeroTitle}>{tx(my,"Pay for analysis, never a guaranteed result.","Analysis အတွက်ပေးချေခြင်းဖြစ်ပြီး အနိုင်ရလဒ်အာမခံမဟုတ်ပါ။")}</Text><Text style={s.marketHeroSub}>Verified record · level price limits · daily publishing limits · permanent wins and losses</Text></View><Ionicons name="analytics-outline" size={33} color={C.red}/></View>{tips.length?tips.map(t=><TipCard key={t.id} tip={t} authenticated={auth} openAccount={openAccount} onUnlock={doUnlock} unlocking={busy===`unlock:${t.id}`} my={my}/>):!loading?<Text style={s.empty}>No premium tips published yet.</Text>:null}</>:null}
    {tab==="TIPSTERS"?<><View style={s.sectionHeader}><Text style={s.sectionTitle}>VERIFIED TIPSTERS</Text><Text style={s.sectionSub}>{tipsters.length} approved</Text></View>{tipsters.length?tipsters.map(x=><TipsterCard key={x.userId} item={x}/>):<Text style={s.empty}>No approved Tipsters yet.</Text>}</>:null}
    {tab==="CREDITS"?<CreditPanel me={me} authenticated={auth} openAccount={openAccount} my={my}/>:null}
    {tab==="TIPSTER"?<>{!auth?<View style={s.statusCard}><Ionicons name="person-circle-outline" size={28} color={C.muted}/><Text style={s.statusTitle}>Tipster account</Text><Text style={s.statusText}>Sign in with your MST account to apply or manage Tipster earnings.</Text><Pressable style={s.primary} onPress={openAccount}><Text style={s.primaryText}>SIGN IN</Text></Pressable></View>:me?.tipster?.status==="approved"?<TipsterDashboard me={me} matches={matches} onPublish={doPublish} onPayout={doPayout} loading={busy==="publish"||busy==="payout"} my={my}/>:<ApplicationPanel me={me} onApply={doApply} loading={busy==="apply"} my={my}/>}</>:null}
  </ScrollView></View>;
}

const s=StyleSheet.create({
  screen:{flex:1,backgroundColor:C.bg},header:{minHeight:70,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:C.border2},title:{fontSize:23,fontWeight:"900",color:C.text},subtitle:{fontSize:9.5,color:C.muted,marginTop:3},headerCoin:{height:34,paddingHorizontal:11,borderRadius:17,backgroundColor:C.card,borderWidth:1,borderColor:C.border,flexDirection:"row",alignItems:"center",gap:6},headerCoinText:{fontSize:11,fontWeight:"900",color:C.gold},tabs:{height:49,padding:6,flexDirection:"row",gap:4,borderBottomWidth:1,borderBottomColor:C.border2},tab:{flex:1,borderRadius:8,alignItems:"center",justifyContent:"center"},tabOn:{backgroundColor:C.redSoft},tabText:{fontSize:8,fontWeight:"900",color:C.muted},tabTextOn:{color:C.red},content:{padding:12,paddingBottom:40},loading:{minHeight:120,alignItems:"center",justifyContent:"center",gap:8},empty:{fontSize:9.5,color:C.muted,textAlign:"center",padding:16},message:{minHeight:38,borderRadius:9,paddingHorizontal:11,backgroundColor:"rgba(34,199,119,.08)",borderWidth:1,borderColor:"rgba(34,199,119,.2)",flexDirection:"row",alignItems:"center",gap:7,marginBottom:8},messageText:{flex:1,fontSize:9.5,color:C.green},errorBox:{minHeight:38,borderRadius:9,paddingHorizontal:11,backgroundColor:C.redSoft,borderWidth:1,borderColor:"rgba(243,39,53,.25)",flexDirection:"row",alignItems:"center",gap:7,marginBottom:8},errorText:{flex:1,fontSize:9.5,color:C.red},
  marketHero:{minHeight:120,borderRadius:15,backgroundColor:C.card,borderWidth:1,borderColor:"rgba(243,39,53,.28)",padding:15,flexDirection:"row",alignItems:"center",gap:12,marginBottom:10},eyebrow:{fontSize:7.5,fontWeight:"900",letterSpacing:.9,color:C.red,marginBottom:5},marketHeroTitle:{fontSize:15,fontWeight:"900",lineHeight:20,color:C.text,maxWidth:270},marketHeroSub:{fontSize:8.5,lineHeight:13,color:C.muted,marginTop:6},
  tipCard:{backgroundColor:C.card,borderRadius:13,borderWidth:1,borderColor:C.border,padding:12,marginBottom:9},tipTop:{flexDirection:"row",alignItems:"center"},competition:{fontSize:10.5,fontWeight:"800",color:C.text2},kickoff:{fontSize:8.5,color:C.muted,marginTop:2},resultBadge:{minWidth:45,height:23,borderRadius:12,alignItems:"center",justifyContent:"center"},resultWin:{backgroundColor:"rgba(34,199,119,.18)"},resultLoss:{backgroundColor:C.redSoft},resultVoid:{backgroundColor:C.card2},resultText:{fontSize:8,fontWeight:"900",color:C.text},matchRow:{minHeight:48,flexDirection:"row",alignItems:"center",gap:8,borderBottomWidth:1,borderBottomColor:C.border2},matchTeam:{flex:1,fontSize:12,fontWeight:"900",color:C.text},vs:{fontSize:8,fontWeight:"900",color:C.muted},tipsterRow:{minHeight:65,flexDirection:"row",alignItems:"center",gap:9},tipsterAvatar:{width:38,height:38,borderRadius:19,backgroundColor:C.card2,alignItems:"center",justifyContent:"center"},tipsterName:{fontSize:10.5,fontWeight:"800",color:C.text2},inline:{flexDirection:"row",alignItems:"center",gap:6,marginTop:4},levelBadge:{height:21,borderRadius:11,borderWidth:1,borderColor:"rgba(243,39,53,.35)",backgroundColor:C.redSoft,paddingHorizontal:6,flexDirection:"row",alignItems:"center",gap:3},levelText:{fontSize:6.8,fontWeight:"900",color:C.red},streak:{fontSize:8.5,fontWeight:"900"},winBox:{alignItems:"flex-end"},winNum:{fontSize:14,fontWeight:"900",color:C.green},winLabel:{fontSize:6.5,fontWeight:"900",color:C.muted},tipMeta:{flexDirection:"row",gap:6,marginBottom:9},metaItem:{flex:1,minHeight:47,borderRadius:8,backgroundColor:C.panel,padding:8,justifyContent:"space-between"},metaLabel:{fontSize:6.8,fontWeight:"800",color:C.muted},metaValue:{fontSize:10,fontWeight:"900",color:C.text2},lockedBox:{borderRadius:10,backgroundColor:C.panel,borderWidth:1,borderColor:C.border,padding:10,flexDirection:"row",alignItems:"center",gap:9},lockedTitle:{fontSize:10,fontWeight:"800",color:C.text2},lockedText:{fontSize:8,lineHeight:12,color:C.muted,marginTop:2},unlockButton:{minWidth:61,height:48,borderRadius:9,backgroundColor:C.red,alignItems:"center",justifyContent:"center"},unlockPrice:{fontSize:16,fontWeight:"900",color:C.text},unlockSmall:{fontSize:6.5,fontWeight:"900",color:C.text,opacity:.85},revealed:{borderRadius:10,backgroundColor:"#0D1511",borderWidth:1,borderColor:"rgba(34,199,119,.25)",padding:11},pickHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},marketName:{fontSize:7.5,fontWeight:"900",color:C.muted},pick:{fontSize:13,fontWeight:"900",color:C.green},analysis:{fontSize:10,lineHeight:15,color:C.text2,marginTop:9},disclaimer:{flexDirection:"row",alignItems:"center",gap:5,marginTop:8},disclaimerText:{flex:1,fontSize:7.4,color:C.muted},
  sectionHeader:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginVertical:6},sectionTitle:{fontSize:11,fontWeight:"900",color:C.text2,marginVertical:8},sectionSub:{fontSize:8.5,color:C.muted},personCard:{minHeight:92,borderRadius:12,backgroundColor:C.card,borderWidth:1,borderColor:C.border,padding:11,flexDirection:"row",alignItems:"center",gap:10,marginBottom:8},personAvatar:{width:46,height:46,borderRadius:23,backgroundColor:C.card2,alignItems:"center",justifyContent:"center"},personName:{fontSize:11.5,fontWeight:"900",color:C.text},personBio:{fontSize:8,lineHeight:12,color:C.muted,marginTop:4},personStats:{alignItems:"flex-end"},personRate:{fontSize:15,fontWeight:"900",color:C.green},personMini:{fontSize:7.5,color:C.muted,marginTop:2},
  walletHero:{minHeight:130,borderRadius:15,backgroundColor:C.card,borderWidth:1,borderColor:"rgba(244,200,77,.28)",padding:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},walletNumber:{fontSize:36,fontWeight:"900",letterSpacing:-1,color:C.text},walletSub:{fontSize:9,color:C.muted,marginTop:2},creditCoin:{width:64,height:64,borderRadius:32,backgroundColor:"rgba(244,200,77,.12)",borderWidth:2,borderColor:C.gold,alignItems:"center",justifyContent:"center"},coinText:{fontSize:16,fontWeight:"900",fontStyle:"italic",color:C.gold},infoCard:{borderRadius:12,backgroundColor:C.card,borderWidth:1,borderColor:C.border,padding:13,marginTop:10},infoTitle:{fontSize:9,fontWeight:"900",color:C.muted},reference:{fontSize:19,fontWeight:"900",color:C.gold,marginTop:5},infoText:{fontSize:9,lineHeight:14,color:C.text2,marginTop:7},packGrid:{flexDirection:"row",flexWrap:"wrap",gap:8},pack:{width:"48%",minHeight:90,borderRadius:11,backgroundColor:C.card,borderWidth:1,borderColor:C.border,padding:12,justifyContent:"center"},packCredits:{fontSize:22,fontWeight:"900",color:C.text},packLabel:{fontSize:7.5,fontWeight:"900",color:C.gold},packPrice:{fontSize:10,color:C.muted,marginTop:7},pendingCard:{marginTop:10,borderRadius:11,backgroundColor:"rgba(244,200,77,.06)",borderWidth:1,borderColor:"rgba(244,200,77,.18)",padding:12,flexDirection:"row",gap:9},pendingTitle:{fontSize:10,fontWeight:"800",color:C.text2},pendingText:{fontSize:8.3,lineHeight:13,color:C.muted,marginTop:3},
  statusCard:{borderRadius:13,backgroundColor:C.card,borderWidth:1,borderColor:C.border,padding:16,alignItems:"center",gap:8},statusTitle:{fontSize:15,fontWeight:"900",color:C.text},statusText:{fontSize:9.5,lineHeight:15,color:C.muted,textAlign:"center",maxWidth:320},formCard:{borderRadius:13,backgroundColor:C.card,borderWidth:1,borderColor:C.border,padding:13,marginBottom:10},formTitle:{fontSize:15,fontWeight:"900",color:C.text},formSub:{fontSize:9,lineHeight:14,color:C.muted,marginTop:4,marginBottom:12},inputLabel:{fontSize:7.5,fontWeight:"900",letterSpacing:.5,color:C.muted,marginTop:10,marginBottom:5},input:{height:44,borderRadius:9,backgroundColor:C.panel,borderWidth:1,borderColor:C.border,paddingHorizontal:11,color:C.text,fontSize:11,marginBottom:2},multiline:{height:90,paddingTop:10,textAlignVertical:"top"},analysisInput:{height:120,paddingTop:10,textAlignVertical:"top"},primary:{height:42,borderRadius:9,backgroundColor:C.red,alignItems:"center",justifyContent:"center",marginTop:12},primaryText:{fontSize:9,fontWeight:"900",color:C.text},secondary:{height:40,borderRadius:9,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center",marginTop:10},secondaryText:{fontSize:9,fontWeight:"900",color:C.text2},disabled:{opacity:.35},
  dashboardHero:{minHeight:100,borderRadius:13,backgroundColor:C.card,borderWidth:1,borderColor:"rgba(243,39,53,.3)",padding:13,flexDirection:"row",alignItems:"center",marginBottom:8},dashboardTitle:{fontSize:17,fontWeight:"900",color:C.text,marginTop:7},dashboardSub:{fontSize:8.5,color:C.muted,marginTop:3},bigRate:{alignItems:"flex-end"},bigRateNum:{fontSize:25,fontWeight:"900",color:C.green},bigRateLabel:{fontSize:7,fontWeight:"900",color:C.muted},statsGrid:{flexDirection:"row",gap:6,marginBottom:9},stat:{flex:1,minHeight:75,borderRadius:10,backgroundColor:C.card,borderWidth:1,borderColor:C.border,padding:9,justifyContent:"space-between"},statLabel:{fontSize:6.8,fontWeight:"900",color:C.muted},statNum:{fontSize:18,fontWeight:"900",color:C.text},statSub:{fontSize:7.3,color:C.muted},matchPicker:{gap:7,paddingBottom:3},matchPick:{width:150,minHeight:94,borderRadius:10,backgroundColor:C.panel,borderWidth:1,borderColor:C.border,padding:9},matchPickOn:{borderColor:C.red,backgroundColor:C.redSoft},matchPickLeague:{fontSize:7.5,fontWeight:"800",color:C.muted},matchPickTeam:{fontSize:9.5,fontWeight:"800",color:C.text2,marginTop:5},matchPickTime:{fontSize:7.5,color:C.red,marginTop:6},chips:{flexDirection:"row",flexWrap:"wrap",gap:6},chip:{minHeight:34,borderRadius:17,backgroundColor:C.panel,borderWidth:1,borderColor:C.border,paddingHorizontal:10,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:C.redSoft,borderColor:C.red},chipText:{fontSize:7.5,fontWeight:"900",color:C.muted},chipTextOn:{color:C.red},priceChip:{minWidth:54,height:36,borderRadius:9,backgroundColor:C.panel,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center"},priceChipOn:{borderColor:C.gold,backgroundColor:"rgba(244,200,77,.08)"},priceChipText:{fontSize:9,fontWeight:"900",color:C.text2},ruleBox:{borderRadius:9,backgroundColor:C.redSoft,padding:10,flexDirection:"row",gap:7,marginTop:8},ruleText:{flex:1,fontSize:8.3,lineHeight:13,color:C.text2},payoutRow:{flexDirection:"row",gap:7}
});
